version: '2'

networks:
  fabric-ca:

services:

  orderer1-org0:
    container_name: orderer1-org0
    build:
      context: .
      dockerfile: fabric-ca-orderer.dockerfile
    environment:
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/orderer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org0-ca-chain.pem
      - ENROLLMENT_URL=https://orderer1-org0:orderer1-org0pw@ica-org0:7054
      - ORDERER_HOME=/etc/hyperledger/orderer
      - ORDERER_HOST=orderer1-org0
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=org0MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/data/org0-ca-chain.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/data/org0-ca-chain.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      - ORG=org0
      - ORG_ADMIN_CERT=/data/orgs/org0/msp/admincerts/cert.pem
    command: /bin/bash -c '/scripts/start-orderer.sh 2>&1 | tee /data/logs/orderer1-org0.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - setup

  peer1-org1:
    container_name: peer1-org1
    build:
      context: .
      dockerfile: fabric-ca-peer.dockerfile
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org1-ca-chain.pem
      - ENROLLMENT_URL=https://peer1-org1:peer1-org1pw@ica-org1:7054
      - PEER_NAME=peer1-org1
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer1-org1
      - PEER_NAME_PASS=peer1-org1:peer1-org1pw
      - CORE_PEER_ID=peer1-org1
      - CORE_PEER_ADDRESS=peer1-org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org1-ca-chain.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org1-ca-chain.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer1-org1-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer1-org1-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org1
      - ORG_ADMIN_CERT=/data/orgs/org1/msp/admincerts/cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer1-org1.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - fabric-ca
    depends_on:
      - setup

  peer2-org1:
    container_name: peer2-org1
    build:
      context: .
      dockerfile: fabric-ca-peer.dockerfile
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org1-ca-chain.pem
      - ENROLLMENT_URL=https://peer2-org1:peer2-org1pw@ica-org1:7054
      - PEER_NAME=peer2-org1
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer2-org1
      - PEER_NAME_PASS=peer2-org1:peer2-org1pw
      - CORE_PEER_ID=peer2-org1
      - CORE_PEER_ADDRESS=peer2-org1:7051
      - CORE_PEER_LOCALMSPID=org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org1-ca-chain.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org1-ca-chain.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer2-org1-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer2-org1-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org1:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org1
      - ORG_ADMIN_CERT=/data/orgs/org1/msp/admincerts/cert.pem
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org1:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer2-org1.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - fabric-ca
    depends_on:
      - setup

  peer1-org2:
    container_name: peer1-org2
    build:
      context: .
      dockerfile: fabric-ca-peer.dockerfile
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org2-ca-chain.pem
      - ENROLLMENT_URL=https://peer1-org2:peer1-org2pw@ica-org2:7054
      - PEER_NAME=peer1-org2
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer1-org2
      - PEER_NAME_PASS=peer1-org2:peer1-org2pw
      - CORE_PEER_ID=peer1-org2
      - CORE_PEER_ADDRESS=peer1-org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org2-ca-chain.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org2-ca-chain.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer1-org2-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer1-org2-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org2
      - ORG_ADMIN_CERT=/data/orgs/org2/msp/admincerts/cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer1-org2.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - fabric-ca
    depends_on:
      - setup

  peer2-org2:
    container_name: peer2-org2
    build:
      context: .
      dockerfile: fabric-ca-peer.dockerfile
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org2-ca-chain.pem
      - ENROLLMENT_URL=https://peer2-org2:peer2-org2pw@ica-org2:7054
      - PEER_NAME=peer2-org2
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer2-org2
      - PEER_NAME_PASS=peer2-org2:peer2-org2pw
      - CORE_PEER_ID=peer2-org2
      - CORE_PEER_ADDRESS=peer2-org2:7051
      - CORE_PEER_LOCALMSPID=org2MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org2-ca-chain.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org2-ca-chain.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer2-org2-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer2-org2-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org2:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org2
      - ORG_ADMIN_CERT=/data/orgs/org2/msp/admincerts/cert.pem
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer2-org2.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /var/run:/host/var/run
    networks:
      - fabric-ca
    depends_on:
      - setup

